import SwiftUI

/// Langues prises en charge par l'application.
enum AppLanguage: String, CaseIterable {
    case fr, en

    var label: String {
        switch self {
        case .fr: return "Français"
        case .en: return "English"
        }
    }

    var flag: String {
        switch self {
        case .fr: return "🇫🇷"
        case .en: return "🇬🇧"
        }
    }

    /// Locale système associée (formats de date, nombres…).
    var locale: Locale {
        switch self {
        case .fr: return Locale(identifier: "fr_FR")
        case .en: return Locale(identifier: "en_US")
        }
    }
}

/// Source de vérité pour la langue choisie. Le changement est appliqué en direct
/// dans toute l'app (RootView se reconstruit via `.id(localizer.language)`).
final class Localizer: ObservableObject {
    static let shared = Localizer()

    @Published var language: AppLanguage {
        didSet { UserDefaults.standard.set(language.rawValue, forKey: Self.key) }
    }

    private static let key = "tripnest.language"

    private init() {
        let raw = UserDefaults.standard.string(forKey: Self.key) ?? AppLanguage.fr.rawValue
        language = AppLanguage(rawValue: raw) ?? .fr
    }
}

/// Traduit un texte français source vers la langue courante.
/// Le français est la clé : pas de table nécessaire, on renvoie le texte tel quel.
/// Pour EN, on cherche dans `TripnestTranslations`. Si absent, on retombe sur le français.
func L(_ fr: String) -> String {
    let lang = Localizer.shared.language
    if lang == .fr { return fr }
    return TripnestTranslations.table[lang]?[fr] ?? fr
}

/// Variante avec interpolation façon `printf` (ex. `L("%d jour", count)`).
func L(_ fr: String, _ args: CVarArg...) -> String {
    String(format: L(fr), arguments: args)
}

/// Tables de traduction EN, indexées par le texte français source.
enum TripnestTranslations {
    static let table: [AppLanguage: [String: String]] = [
        .en: en,
    ]

    // MARK: English
    static let en: [String: String] = [
        // Navigation / TabBar
        "Accueil": "Home",
        "Voyages": "Trips",
        "Budget": "Budget",
        "Profil": "Profile",
        "Spots": "Spots",
        "Transport": "Transport",

        // Profil
        "Mon profil": "My profile",
        "Modifier le profil": "Edit profile",
        "PRÉFÉRENCES": "PREFERENCES",
        "COMPTE": "ACCOUNT",
        "Devise par défaut": "Default currency",
        "Ajouter un ami": "Add a friend",
        "Nom de l'ami": "Friend's name",
        "Nom de l'ami Tripnest": "Tripnest friend's name",
        "MES AMIS": "MY FRIENDS",
        "Supprimer": "Delete",
        "Envoyer l'invitation": "Send invitation",
        "SUGGESTIONS": "SUGGESTIONS",
        "En attente": "Pending",
        "Invitation acceptée": "Invitation accepted",
        "%@ a accepté ton invitation.": "%@ accepted your invitation.",
        "Aucun utilisateur ne porte ce nom.": "No user found with this name.",
        "Cet ami est déjà dans ta liste.": "This friend is already in your list.",
        "Notifications": "Notifications",
        "Langue": "Language",
        "Français": "English",
        "Documents · passeport, ID": "Documents · passport, ID",
        "Aide & support": "Help & support",
        "Se déconnecter": "Sign out",
        "Nom affiché": "Display name",
        "Ex. Lucas Martin": "E.g. Lucas Martin",
        "Enregistrer": "Save",
        "Fermer": "Close",
        "Mes documents": "My documents",
        "Stocke ici tes documents de voyage importants.": "Store your important travel documents here.",
        "Passeport": "Passport",
        "Carte d'identité": "ID card",
        "Visa / autorisation": "Visa / permit",
        "Assurance voyage": "Travel insurance",
        "Ajouter": "Add",
        "Pour toute question ou problème, contacte-nous à :": "For any question or issue, contact us at:",
        "Photo de profil": "Profile photo",
        "Prendre une photo": "Take a photo",
        "Choisir dans la galerie": "Choose from gallery",
        "Supprimer la photo": "Remove photo",
        "Annuler": "Cancel",
        "amis": "friends",
        "spots": "spots",
        "voyage(s)": "trip(s)",
        "dépense(s)": "expense(s)",
        "Changer la photo de profil": "Change profile photo",
        "Ajouté · touche pour remplacer": "Added · tap to replace",
        "Partager": "Share",
        "Appuie ici seulement si tu veux inviter quelqu'un.": "Tap here only if you want to invite someone.",
        "Choisis ce que ton ami pourra faire avant d'envoyer l'invitation.": "Choose what your friend can do before sending the invitation.",
        "Invite un ami qui a Tripnest": "Invite a friend who has Tripnest",
        "Inviter": "Invite",
        "Membre depuis %@": "Member since %@",
        "Mes amis (%d)": "My friends (%d)",
        "Après confirmation, tu devras attendre 30 jours avant de pouvoir changer ton nom à nouveau.": "After confirming, you'll need to wait 30 days before you can change your name again.",
        "Prochain changement dans %d jour": "Next change in %d day",
        "Prochain changement dans %d jours": "Next change in %d days",
        "Ton nom s'affichera sur ton accueil et ton profil.": "Your name will appear on your home screen and profile.",
        "Profil prêt à sauvegarder": "Profile ready to save",
        "Ce profil évoluera avec tes vrais voyages.": "This profile will grow with your real trips.",

        // Commun
        "Amis du voyage": "Trip friends",
        "Aucun ami invité": "No friends invited",
        "Date de départ": "Departure date",
        "Invite un ami depuis la création ou le partage du voyage.": "Invite a friend when creating or sharing the trip.",
        "Étape 1 sur 4 · ne ferme pas l'app": "Step 1 of 4 · don't close the app",
        "Étape 2 sur 4 · ne ferme pas l'app": "Step 2 of 4 · don't close the app",
        "Confirmer": "Confirm",
        "Retour": "Return",
        "Revenir": "Back",
        "Réessayer": "Try again",
        "Modifier": "Edit",
        "Changer": "Change",
        "Retirer": "Remove",
        "Utiliser": "Use",
        "Terminé": "Done",
        "Prêt": "Ready",
        "OK": "OK",
        "Date": "Date",
        "Heure": "Time",
        "Note": "Note",
        "Titre": "Title",
        "Récap": "Summary",
        "Récapitulatif": "Summary",
        "Détails": "Details",
        "Données": "Data",
        "Données locales": "Local data",
        "Données locales · ": "Local data · ",
        "Local": "Local",
        "Locales": "Local",
        "privées": "private",
        "Aucun résultat": "No results",

        // Home
        "Définis ton budget": "Set your budget",
        "Mon carnet de voyages": "My travel journal",
        "Crée ton premier voyage pour démarrer": "Create your first trip to get started",
        "Aucun voyage pour le moment": "No trips yet",
        "Aucun voyage actif": "No active trip",
        "Ton voyage": "Your trip",
        "Petit rappel sur les onglets de Tripnest.": "A quick reminder about Tripnest's tabs.",
        "À quoi servent les onglets": "What the tabs are for",
        "Comment fonctionne Tripnest ?": "How does Tripnest work?",

        // Trips
        "Voyages en cours": "Ongoing trips",
        "Voyages faits": "Completed trips",
        "Voyages passés": "Past trips",
        "VOYAGES EN COURS": "ONGOING TRIPS",
        "VOYAGES FAITS": "COMPLETED TRIPS",
        "VOYAGES PASSÉS": "PAST TRIPS",
        "EN COURS": "ONGOING",
        "TERMINÉS": "COMPLETED",
        "Voyage total (%d)": "Total trips (%d)",
        "Appuie sur un voyage pour voir tous ses détails.": "Tap a trip to see all its details.",
        "Aucun voyage disponible": "No trips available",
        "Aucun voyage sélectionné": "No trip selected",
        "Aucun voyage à afficher": "No trips to display",
        "Aucun voyage terminé": "No completed trips",
        "Tous tes voyages sont archivés": "All your trips are archived",
        "Coche « Voyage fait » sur un voyage en cours pour le retrouver ici.": "Check “Trip done” on an ongoing trip to find it here.",
        "Tes voyages terminés apparaîtront ici avec leurs vraies photos et notes.": "Your completed trips will appear here with their real photos and notes.",
        "Retrouve-les dans l'onglet Voyages → Voyages passés, ou crée un nouveau voyage.": "Find them in the Trips tab → Past trips, or create a new trip.",
        "Crée un voyage, ajoute tes dépenses, puis Tripnest calcule le reste.": "Create a trip, add your expenses, then Tripnest does the rest.",
        "Pour créer un voyage, utilise l'onglet Accueil.": "To create a trip, use the Home tab.",
        "Remettre dans les voyages en cours": "Move back to ongoing trips",
        "Archiver": "Archive",
        "Archiver ce voyage ?": "Archive this trip?",
        "Archiver dans les voyages passés": "Archive to past trips",
        "Oui, archiver": "Yes, archive",
        "Partager ce voyage": "Share this trip",
        "Partager le voyage": "Share the trip",
        "Supprimer ce voyage": "Delete this trip",
        "Supprimer ce voyage ?": "Delete this trip?",
        "Cette action est définitive.": "This action is permanent.",
        "Chargement du voyage…": "Loading trip…",
        "Impossible de charger ce voyage.": "Unable to load this trip.",
        "Destination à définir": "Destination to be set",
        "Dates à définir · durée à définir": "Dates to be set · duration to be set",
        "Mon calendrier": "My calendar",
        "Tes voyages\nau même endroit": "Your trips\nin one place",
        "Plus récents ⌄": "Most recent ⌄",

        // Budget
        "Budget total": "Total budget",
        "Modifier le budget": "Edit budget",
        "Démarre à 0€": "Starts at €0",
        "Dépenses": "Expenses",
        "Dépensé": "Spent",
        "Disponible réel": "Actual available",
        "Fond d'urgence": "Emergency fund",
        "Urgence": "Emergency",
        "MES DÉPENSES": "MY EXPENSES",
        "MONTANT": "AMOUNT",
        "PAR CATÉGORIE": "BY CATEGORY",
        "CATÉGORIE": "CATEGORY",
        "Nouvelle catégorie": "New category",
        "Supprimer cette catégorie ?": "Delete this category?",
        "Supprimer la catégorie %@": "Delete category %@",
        "La catégorie « %@ » sera supprimée.": "The category “%@” will be deleted.",
        "Aucune dépense enregistrée": "No expenses recorded",
        "Ajoute tes dépenses réelles pour suivre ton budget.": "Add your real expenses to track your budget.",
        "Ajoute un montant pour suivre tes dépenses pendant le voyage.": "Add an amount to track your spending during the trip.",
        "Choisis un voyage pour gérer son budget.": "Choose a trip to manage its budget.",
        "Choisis une couleur": "Choose a color",
        "Choisir une devise": "Choose a currency",
        "Crée ou ouvre un voyage depuis l'onglet Voyages pour gérer son budget ici.": "Create or open a trip from the Trips tab to manage its budget here.",
        "Crée d'abord un voyage": "Create a trip first",
        "Une dépense doit être rattachée à un voyage réel.": "An expense must be linked to a real trip.",
        "Un budget clair commence avec tes propres dépenses": "A clear budget starts with your own expenses",
        "Suis tes dépenses en temps réel pour décider avec tes propres chiffres.": "Track your spending in real time to decide with your own numbers.",
        "%d%% utilisé": "%d%% used",
        "%@ dépensés": "%@ spent",
        "%@ dépensé": "%@ spent",
        "Ce fond sera retiré du portefeuille urgence.": "This fund will be removed from the emergency wallet.",
        "Modifier ce fond": "Edit this fund",
        "Supprimer ce fond": "Delete this fund",
        "Supprimer ce fond ?": "Delete this fund?",
        "Retirer ce fond": "Remove this fund",
        "Détails de l'urgence…": "Emergency details…",
        "DANS LE FOND": "IN THE FUND",
        "Convertir les devises": "Convert currencies",
        "Convertisseur": "Converter",
        "Convertisseur de devises": "Currency converter",
        "Taux indisponible": "Rate unavailable",
        "Tarif non configuré": "Rate not configured",
        "OBJECTIF": "GOAL",
        "COULEUR": "COLOR",
        "Modifier ou supprimer une activité avec les icônes à droite.": "Edit or delete an activity with the icons on the right.",

        // Add expense
        "Supprimer cette dépense": "Delete this expense",
        "Supprimer cette dépense ?": "Delete this expense?",
        "dépense enregistrée": "expense saved",
        "Détails, reçu, anecdote…": "Details, receipt, story…",
        "Note (facultatif)": "Note (optional)",
        "Lieu (facultatif)": "Place (optional)",
        "Ex. réparation, médicament, taxi…": "E.g. repair, medication, taxi…",
        "Ex. 25 € / pers": "E.g. €25 / person",
        "Coup de cœur": "Favorite",
        "VOYAGE LIÉ": "LINKED TRIP",
        "TYPE": "TYPE",
        "STATUT": "STATUS",

        // Spots
        "Ajouter un spot": "Add a spot",
        "Rechercher un spot": "Search a spot",
        "Supprimer ce spot": "Delete this spot",
        "Supprimer ce spot ?": "Delete this spot?",
        "Localiser ce spot sur la carte": "Locate this spot on the map",
        "Centrer sur ma position": "Center on my location",
        "Voir sur la planète": "View on the globe",
        "Essaie d'ajuster ta recherche ou ta catégorie.": "Try adjusting your search or category.",
        "Ex : Bar, Café, Musée…": "E.g. Bar, Café, Museum…",
        "Ex. Bar, Café, Musée…": "E.g. Bar, Café, Museum…",
        "ADRESSE": "ADDRESS",
        "Adresse détectée": "Detected address",
        "Ex. 1 Rue de Rivoli, Paris": "E.g. 1 Rue de Rivoli, Paris",

        // Planning
        "Planifie ton programme": "Plan your schedule",
        "Planifier une étape": "Plan a stage",
        "Planifie ton premier trajet en quelques étapes.": "Plan your first trip in a few steps.",
        "Programme du %@": "Schedule for %@",
        "Pour le %@": "For %@",
        "%d étape": "%d stage",
        "%d étapes": "%d stages",
        "Aucune étape planifiée": "No stage planned",
        "Aucune activité ce jour-là.\nAppuie sur « Planifie ton programme » pour en ajouter une.": "No activity that day.\nTap “Plan your schedule” to add one.",
        "Nom de l’activité": "Activity name",
        "Ex : Musée, Déjeuner…": "E.g. Museum, Lunch…",
        "Ex : Centre-ville, Hôtel…": "E.g. Downtown, Hotel…",
        "Mode de transport": "Transport mode",
        "Durée du trajet": "Trip duration",
        "Heures": "Hours",
        "Minutes": "Minutes",
        "Détails, adresse, rappels…": "Details, address, reminders…",
        "Les rappels sont mis à jour quand tu ajoutes ou modifies une activité.": "Reminders are updated when you add or edit an activity.",
        "Rappels liés à ce voyage uniquement. Tu seras prévenu 1 h à l’avance.": "Reminders linked to this trip only. You'll be notified 1 hour ahead.",
        "PLAN DU TRAJET": "TRIP PLAN",
        "PROCHAINE ESCALE": "NEXT STOP",
        "PROCHAINES ÉTAPES": "NEXT STAGES",
        "PROJECTION SUR 12 MOIS": "12-MONTH PROJECTION",

        // Souvenirs
        "Souvenirs": "Memories",
        "SOUVENIRS": "MEMORIES",
        "Aucun souvenir pour le moment": "No memories yet",
        "Aucune photo pour l'instant": "No photos yet",
        "Ajoute tes souvenirs : paysages, billets, moments…": "Add your memories: landscapes, tickets, moments…",
        "Ajoute une photo, une date, un titre et une description (150 lignes max).": "Add a photo, a date, a title and a description (150 lines max).",
        "Ajouter titre & description": "Add title & description",
        "Titre du souvenir": "Memory title",
        "Raconte ce moment…": "Tell this moment…",
        "Pince pour zoomer, glisse pour repositionner.": "Pinch to zoom, drag to reposition.",
        "Recadrer la couverture": "Crop the cover",
        "Cette photo sera définitivement supprimée.": "This photo will be permanently deleted.",
        "Supprimer cette photo ?": "Delete this photo?",
        "%d photo": "%d photo",
        "%d photos": "%d photos",
        "PHOTOS": "PHOTOS",
        "PHOTOS DU VOYAGE": "TRIP PHOTOS",
        "Galerie": "Gallery",
        "Appareil photo": "Camera",
        "Sans titre": "Untitled",

        // Notes
        "MES NOTES": "MY NOTES",
        "Écris tes notes pour ce voyage : adresses, idées, rappels…": "Write your notes for this trip: addresses, ideas, reminders…",
        "Ajoute une note, une impression, une anecdote…": "Add a note, an impression, a story…",
        "DESCRIPTION": "DESCRIPTION",
        "TITRE": "TITLE",
        "NOM": "NAME",

        // Flights / tickets
        "Vols & billets": "Flights & tickets",
        "Gérer les vols": "Manage flights",
        "Ajoute ton billet pour l'afficher ici.": "Add your ticket to display it here.",
        "Billet non reconnu": "Ticket not recognized",
        "Lecture du billet…": "Reading ticket…",
        "Scanner": "Scan",
        "Format carte": "Card format",
        "DÉPART": "DEPARTURE",
        "DÉTAILS": "DETAILS",
        "DÉTAILS DU VOYAGE": "TRIP DETAILS",
        "ENREGISTREMENTS": "CHECK-INS",
        "IMAGE DE FOND": "BACKGROUND IMAGE",

        // Notifications
        "Rappels": "Reminders",
        "RAPPELS INTELLIGENTS": "SMART REMINDERS",
        "Activer les notifications": "Enable notifications",
        "Notifications désactivées": "Notifications disabled",
        "Notifications iOS désactivées": "iOS notifications disabled",
        "Active les notifications Tripnest dans Réglages pour recevoir tes rappels de voyage.": "Enable Tripnest notifications in Settings to receive your trip reminders.",
        "Active les notifications dans Réglages iOS pour recevoir tes rappels de planification.": "Enable notifications in iOS Settings to receive your planning reminders.",
        "Autorise les alertes iOS pour tes rappels de budget, vols et spots.": "Allow iOS alerts for your budget, flight and spot reminders.",
        "Autorise les notifications pour activer les rappels ci-dessous.": "Allow notifications to enable the reminders below.",
        "Ouvrir Réglages": "Open Settings",
        "Réglages": "Settings",

        // Login
        "Bon retour !": "Welcome back!",
        "Création de compte": "Create account",
        "Mot de passe oublié": "Forgot password",
        "Aucun paiement configuré dans cette version.": "No payment configured in this version.",

        // Cover / photo
        "Image de couverture": "Cover image",

        // Onboarding
        "BIENVENUE": "WELCOME",
        "BIENVENUE DANS TRIPNEST": "WELCOME TO TRIPNEST",
        "BONNE NOUVELLE": "GOOD NEWS",
        "Tripnest": "Tripnest",
        "Tripnest.": "Tripnest.",
        "On va te poser quelques questions.\n2 minutes pour préparer ton espace voyage.": "We'll ask you a few questions.\n2 minutes to set up your travel space.",
        "Tes réponses vont servir à préparer ton espace.": "Your answers will be used to set up your space.",
        "Comment t'organises-tu\naujourd'hui ?": "How do you organize\nyourself today?",
        "Comment voyages-tu ?": "How do you travel?",
        "Je n'ai pas encore de plan précis →": "I don't have a precise plan yet →",
        "Pourquoi as-tu téléchargé\nTripnest aujourd'hui ?": "Why did you download\nTripnest today?",
        "Quel est ton objectif\nnuméro 1 cette année ?": "What's your number 1\ngoal this year?",
        "Quel est ton plus gros défi\nquand tu voyages ?": "What's your biggest challenge\nwhen you travel?",
        "Qu'est-ce qui te frustre\nle plus avec ces outils ?": "What frustrates you\nmost with these tools?",
        "Combien dépenses-tu\npar voyage en moyenne ?": "How much do you spend\nper trip on average?",
        "Combien veux-tu économiser\nsur ton prochain voyage ?": "How much do you want to save\non your next trip?",
        "As-tu déjà dépassé ton\nbudget en voyage ?": "Have you ever gone over your\nbudget while traveling?",
        "De combien as-tu dépassé\nen moyenne ?": "By how much did you go over\non average?",
        "Avec qui voyages-tu\nle plus souvent ?": "Who do you travel with\nmost often?",
        "AVEC QUI TU VAS VOYAGER ?": "WHO WILL YOU TRAVEL WITH?",
        "Où as-tu envie d'aller\nen priorité ?": "Where do you want to go\nfirst?",
        "Où as-tu envie\nd'aller ?": "Where do you want\nto go?",
        "À quelle fréquence\npars-tu en voyage ?": "How often\ndo you travel?",
        "Comment doit-on\nt'appeler ": "What should we\ncall you ",
        "On adaptera les suggestions de lieux selon ton choix.": "We'll adapt place suggestions to your choice.",
        "On croise tes 15 réponses pour construire un plan vraiment perso.": "We cross-check your 15 answers to build a truly personal plan.",
        "On prépare une base que tu pourras remplacer par tes vraies données.": "We prepare a base you can replace with your real data.",
        "On t'aide à tenir\ntes objectifs.": "We help you reach\nyour goals.",
        "On va construire ton plan\nen 4 étapes": "We'll build your plan\nin 4 steps",
        "Ton budget sera ": "Your budget will be ",
        "Garde le contrôle\nde ton budget": "Stay in control\nof your budget",
        "Des écrans branchés\nsur tes données.": "Screens connected\nto your data.",
        "Décollage\nimminent.": "Takeoff\nimminent.",
        "Lance ton espace\n": "Launch your space\n",
        "Le plan se remplira avec ": "The plan will fill with ",
        "Le saviez-vous": "Did you know",
        "Tu es une\n": "You are a\n",
        "Tu as tout pour réussir\nton objectif": "You have everything to reach\nyour goal",
        "Tout est calibré\npour toi.": "Everything is calibrated\nfor you.",
        "Tu peux maintenant entrer dans l'app.": "You can now enter the app.",
        "Tu pourras ajouter tes voyages, dépenses et lieux dès l'écran d'accueil.": "You'll be able to add your trips, expenses and places right from the home screen.",
        "Ton espace Tripnest t'attend.\nL'aventure commence maintenant.": "Your Tripnest space awaits.\nThe adventure begins now.",
        "Ton espace local\nest prêt.": "Your local space\nis ready.",
        "Ton plan complet\nest prêt à décoller.": "Your full plan\nis ready for takeoff.",
        "Ton prochain voyage\ndéjà esquissé pour toi.": "Your next trip\nalready sketched out for you.",
        "Ton suivi va se baser\nsur tes dépenses.": "Your tracking will be based\non your spending.",
        "Calibrage du budget…": "Calibrating budget…",
        "Analyse de ton profil…": "Analyzing your profile…",
        "ANALYSE": "ANALYSIS",
        "ANALYSE TERMINÉE": "ANALYSIS COMPLETE",
        "MICRO-INSIGHT": "MICRO-INSIGHT",
        "Ce qui compte": "What matters",
        "FAIT POUR TOI": "MADE FOR YOU",
        "CE QUE TU VAS UTILISER": "WHAT YOU'LL USE",
        "INCLUS DANS TON PLAN": "INCLUDED IN YOUR PLAN",
        "DERNIÈRE LIGNE DROITE": "FINAL STRETCH",
        "DERNIÈRE ÉTAPE": "LAST STEP",
        "OPTION À BRANCHER PLUS TARD": "OPTION TO CONNECT LATER",
        "OPTIONNEL": "OPTIONAL",
        "SAUVEGARDE TON PROFIL": "SAVE YOUR PROFILE",
        "PROFIL SAUVEGARDÉ": "PROFILE SAVED",
        "TON ESPACE EST PRÊT": "YOUR SPACE IS READY",
        "TON PLAN PERSONNALISÉ": "YOUR PERSONALIZED PLAN",
        "TU N'ES PAS SEUL·E": "YOU'RE NOT ALONE",
        "TOI": "YOU",
        "Réaliste": "Realistic",
        "Voyageur organisé": "Organized traveler",
        "Voyage total": "Total trip",
        "Tu aimes voyager en autonomie, mais tu veux du contrôle. Tu optimises sans sacrifier le plaisir.": "You like to travel independently, but you want control. You optimize without sacrificing fun.",
        "Aucun compte requis pour commencer. Les données créées dans l'app restent locales pour l'instant.": "No account required to start. Data created in the app stays local for now.",
        "Espace local · activé": "Local space · enabled",
        "Espace local": "Local space",
        "Données locales · activé": "Local data · enabled",
        "100 % local": "100% local",
        "Sur 4 voyages par an, ça fait ": "Over 4 trips a year, that's ",
        "1 520€ par an": "€1,520 per year",
        "≈ 230€ / jour pour 8 jours": "≈ €230 / day for 8 days",
        "1 520€": "€1,520",
        "moins de 100€": "less than €100",
        "par voyage en moyenne": "per trip on average",
        "selon ton budget réel": "based on your real budget",
        "basé sur tes saisies": "based on your entries",
        "tes vrais voyages": "your real trips",
        "avant d'ajouter tes vraies dépenses": "before adding your real expenses",
        "sauvés": "saved",
        "stockées sur l'appareil": "stored on the device",
        " de perte.": " of loss.",
        " — il sera ajusté avec tes vraies dépenses dans l'app.": " — it will be adjusted with your real expenses in the app.",
        " — tes données restent sur ton appareil.": " — your data stays on your device.",
        ", pas sur des exemples.": ", not on examples.",
        ", tes dépenses et tes lieux sauvegardés.": ", your expenses and saved places.",
        "0 exemple": "0 example",
        "0 personne regarde ce voyage": "0 people watching this trip",
        "Avr": "Apr",
        "Déc": "Dec",
        "Jan": "Jan",
        "Juil": "Jul",
        "Oct": "Oct",
        "G": "G",
        "Annuel · 7 jours offerts": "Yearly · 7 days free",
        "Mensuel": "Monthly",
        " Aéroport": " Airport",
        " Aéroport International": " International Airport",
        "Aéroport ": "Airport ",
        " · Retour": " · Return",
        "%d personne peut accéder à ce voyage.": "%d person can access this trip.",
        "%d personnes peuvent accéder à ce voyage.": "%d people can access this trip.",
        "1 h avant chaque activité": "1 hr before each activity",
        "1 h avant le départ": "1 hr before departure",
        "1–2 voyages": "1–2 trips",
        "24h avant chaque départ": "24h before each departure",
        "4+ voyages": "4+ trips",
        "Activité": "Activity",
        "Activités": "Activities",
        "Activées": "Enabled",
        "Adresse non reconnue. Choisis une suggestion ou une adresse complète.": "Address not recognized. Choose a suggestion or a complete address.",
        "Adresses oubliées, restos perdus": "Forgotten addresses, lost restaurants",
        "Adresses, idées et rappels, jusqu'à 500 lignes.": "Addresses, ideas and reminders, up to 500 lines.",
        "Ajoute tes restaurants, hôtels ou activités pour les retrouver pendant ton voyage.": "Add your restaurants, hotels or activities to find them during your trip.",
        "Ajoute tes vrais billets": "Add your real tickets",
        "Ajoute ton billet pour retrouver horaires et détails ici.": "Add your ticket to find schedules and details here.",
        "Ajoute une date de départ au voyage pour activer ce rappel": "Add a departure date to the trip to enable this reminder",
        "Ajouter au budget": "Add to budget",
        "Ajouter au fond": "Add to fund",
        "Ajouter aux coups de cœur": "Add to favorites",
        "Ajouter budget": "Add budget",
        "Ajouter le départ": "Add departure",
        "Ajouter le retour": "Add return",
        "Ajouter un billet": "Add a ticket",
        "Ajouter un vol": "Add a flight",
        "Ajouter une date": "Add a date",
        "Ajouter une dépense": "Add an expense",
        "Alerte dépassement de budget": "Budget overrun alert",
        "Alertes budget intelligentes": "Smart budget alerts",
        "Ami Tripnest": "Tripnest friend",
        "Analyse de ton profil": "Analyzing your profile",
        "Arrivée (code)": "Arrival (code)",
        "Arrivée ?": "Arrival?",
        "Aucun billet enregistré": "No ticket saved",
        "Aucun spot enregistré": "No spot saved",
        "Aucun vol enregistré": "No flight saved",
        "Aucun voyage en cours": "No ongoing trip",
        "Aucune dépense planifiée.": "No planned expense.",
        "Aucune vision d'ensemble": "No overall picture",
        "Avant que tu atteignes 100%": "Before you reach 100%",
        "Avec enfants": "With kids",
        "Aéroports du monde entier": "Airports worldwide",
        "BUDGET\nRESTANT": "BUDGET\nLEFT",
        "Bilan hebdo de tes économies": "Weekly savings report",
        "Billet à compléter": "Ticket to complete",
        "Bon après-midi": "Good afternoon",
        "Budget calibré": "Budget calibrated",
        "Budget dépassé": "Budget exceeded",
        "Budget initialisé": "Budget initialized",
        "Budget réel": "Real budget",
        "C'est même devenu une habitude": "It's even become a habit",
        "Calibrage de ton budget": "Calibrating your budget",
        "Carte, espèces…": "Card, cash…",
        "Catégories pas adaptées au voyage": "Categories not suited to travel",
        "Cette année, c'est la bonne": "This year is the one",
        "Chaque dépense ajoutée met ton budget à jour.": "Each added expense updates your budget.",
        "Chargement de la carte…": "Loading map…",
        "Chloé Moreau": "Chloé Moreau",
        "Choisis au moins 3 destinations.": "Choose at least 3 destinations.",
        "Choisis ou crée un voyage pour y rattacher tes vols.": "Choose or create a trip to link your flights to it.",
        "Choisis un voyage en cours, définis ton budget puis suis tes dépenses par catégorie.": "Choose an ongoing trip, set your budget then track your spending by category.",
        "Choisis un voyage pour enregistrer tes spots.": "Choose a trip to save your spots.",
        "Coché": "Checked",
        "Compagnie aérienne": "Airline",
        "Construction · 1/4": "Building · 1/4",
        "Construction · 2/4": "Building · 2/4",
        "Construire mon plan": "Build my plan",
        "Construire mon plan voyage": "Build my travel plan",
        "Consulte tes dépenses et ajoute-en de nouvelles.": "Review your expenses and add new ones.",
        "Créer un voyage": "Create a trip",
        "Créer voyage": "Create trip",
        "DESTINATIONS RÊVÉES": "DREAM DESTINATIONS",
        "Dans 1 jour": "In 1 day",
        "Dans le budget": "Within budget",
        "Date et heure de départ": "Departure date and time",
        "Date à définir": "Date to be set",
        "Dates à définir": "Dates to be set",
        "Durée": "Duration",
        "DÉPART AUJOURD'HUI": "DEPARTING TODAY",
        "DÉPART DEMAIN": "DEPARTING TOMORROW",
        "DÉPENSES EFFECTUÉES": "PAID EXPENSES",
        "DÉPENSES À VENIR": "UPCOMING EXPENSES",
        "Définir": "Set",
        "Définir un budget": "Set a budget",
        "Déjà payée, compte dans le budget": "Already paid, counts in the budget",
        "Déjà visité": "Already visited",
        "Départ": "Departure",
        "Départ (code)": "Departure (code)",
        "Départ ?": "Departure?",
        "Départ aujourd'hui": "Departing today",
        "Départ dans 1 h": "Departure in 1 hr",
        "Départ · date à définir": "Departure · date to be set",
        "Dépassement": "Overrun",
        "Dépasser mon budget": "Going over my budget",
        "Dépassé": "Exceeded",
        "Dépense effectuée": "Expense paid",
        "Dépense à venir": "Upcoming expense",
        "Désactivées": "Disabled",
        "EN PRÉPARATION": "IN PREPARATION",
        "En préparation": "In preparation",
        "Enregistrer la dépense": "Save expense",
        "Enregistrer les modifications": "Save changes",
        "Entrer dans Tripnest": "Enter Tripnest",
        "Entrer dans Tripnest →": "Enter Tripnest →",
        "Espace local sécurisé": "Secure local space",
        "Et c'est pour ça que je suis ici": "And that's why I'm here",
        "Ex. Le Marais, gare…": "E.g. Le Marais, station…",
        "Ex. Lyon-Saint Exupéry": "E.g. Lyon-Saint Exupéry",
        "Ex. déjeuner, hôtel, taxi": "E.g. lunch, hotel, taxi",
        "Faire le voyage de ma vie": "Take the trip of my life",
        "Fermer la recherche": "Close search",
        "Fonctions clés": "Key features",
        "Garder mes souvenirs": "Keep my memories",
        "Garder une trace propre": "Keep a clean record",
        "Heure d'arrivée": "Arrival time",
        "Heure de départ": "Departure time",
        "Hébergement": "Accommodation",
        "Hôtel": "Hotel",
        "Indique où tu repars au retour": "Set where you leave from on the way back",
        "Indépendant·e": "Independent",
        "Inutile en plein voyage": "Useless mid-trip",
        "Itinéraire": "Itinerary",
        "J'ai des destinations en tête à concrétiser": "I have destinations in mind to make happen",
        "J'ai déjà dépassé mon budget une fois de trop": "I've gone over budget one too many times",
        "J'ai déjà un compte": "I already have an account",
        "Je découvre les dégâts au retour": "I discover the damage when I get back",
        "Je finis par ne plus le faire": "I end up not doing it anymore",
        "Je ne sais jamais où j'en suis": "I never know where I stand",
        "Je ne suis pas vraiment mon budget": "I don't really track my budget",
        "Je perds le contrôle vite": "I lose control fast",
        "Je perds les lieux découverts": "I lose the places I discover",
        "Je veux garder le contrôle →": "I want to stay in control →",
        "Jours": "Days",
        "L'app de ma banque": "My bank's app",
        "Lancer la construction →": "Start building →",
        "Le lundi matin": "On Monday morning",
        "Les conversions de devises": "Currency conversions",
        "Lieu d'arrivée": "Arrival place",
        "Lieu de départ": "Departure place",
        "Lieu non reconnu. Choisis une suggestion dans la liste.": "Place not recognized. Choose a suggestion from the list.",
        "Long séjour": "Long stay",
        "Léa Dubois": "Léa Dubois",
        "MONTANT À AJOUTER": "AMOUNT TO ADD",
        "Mais je veux optimiser quand même": "But I still want to optimize",
        "Mais ça ne me convient pas": "But it doesn't suit me",
        "Marquer comme déjà fait": "Mark as already done",
        "Marquer comme effectuée": "Mark as paid",
        "Marquer comme non visité": "Mark as not visited",
        "Marquer comme à venir": "Mark as upcoming",
        "Mes ferries": "My ferries",
        "Mes photos s'éparpillent": "My photos get scattered",
        "Mes trains": "My trains",
        "Mes vols": "My flights",
        "Mes voyages partent dans l'oubli": "My trips fade into oblivion",
        "Mes voyages sont chaotiques": "My trips are chaotic",
        "Mieux planifier mes vacances": "Better plan my vacations",
        "Modifier la dépense": "Edit expense",
        "Modifier le spot": "Edit spot",
        "Modifier le voyage": "Edit trip",
        "Modifier l’activité": "Edit activity",
        "Mon billet d'avion": "My plane ticket",
        "Mon billet de ferry": "My ferry ticket",
        "Mon billet de train": "My train ticket",
        "NOUVEAU BUDGET TOTAL": "NEW TOTAL BUDGET",
        "Nom du lieu": "Place name",
        "Non coché": "Unchecked",
        "Notes du voyage": "Trip notes",
        "Notifications activées": "Notifications enabled",
        "Nouveau voyage": "New trip",
        "Nouvelle activité": "New activity",
        "Nouvelle dépense": "New expense",
        "Numéro de train": "Train number",
        "Numéro de traversée": "Crossing number",
        "Numéro de vol": "Flight number",
        "OBJECTIF PRINCIPAL": "MAIN GOAL",
        "Objectif d'économie": "Savings goal",
        "On ajuste avec tes réponses": "We adjust with your answers",
        "On croise tes 15 réponses": "We cross-check your 15 answers",
        "On l'utilise pour construire ton premier plan. Tu pourras ajouter les dates plus tard.": "We use it to build your first plan. You can add the dates later.",
        "On prépare ton objectif": "We prepare your goal",
        "Oublier les détails": "Forgetting the details",
        "Oui, une fois ou deux": "Yes, once or twice",
        "Ouvrir le budget": "Open budget",
        "Ouvrir les notes": "Open notes",
        "PLANIFIER\nÉTAPES": "PLAN\nSTAGES",
        "POUR COMMENCER": "TO GET STARTED",
        "Partager avec un·e ami·e": "Share with a friend",
        "Pas de jugement. Juste pour calibrer ton plan.": "No judgment. Just to calibrate your plan.",
        "Payé avec": "Paid with",
        "Peut modifier": "Can edit",
        "Photos du voyage": "Trip photos",
        "Planifié": "Planned",
        "Plus rarement, mais je rêve": "More rarely, but I dream",
        "Pour chaque heure planifiée dans ton calendrier": "For each time planned in your calendar",
        "Prends une photo plus nette ou saisis le billet à la main.": "Take a clearer photo or enter the ticket manually.",
        "Profil voyageur": "Traveler profile",
        "Profil voyageur calibré": "Traveler profile calibrated",
        "Profil voyageur à affiner": "Traveler profile to refine",
        "Préférences d'onboarding enregistrées": "Onboarding preferences saved",
        "Préparation de ton premier voyage…": "Preparing your first trip…",
        "Préparer mon espace →": "Set up my space →",
        "Prévue, pas encore payée": "Planned, not yet paid",
        "Prête à organiser tes voyages": "Ready to organize your trips",
        "Pérou": "Peru",
        "Q1 · TON STYLE": "Q1 · YOUR STYLE",
        "Q2 · FRÉQUENCE": "Q2 · FREQUENCY",
        "Q3 · MOMENT DE VÉRITÉ": "Q3 · MOMENT OF TRUTH",
        "Q4 · DE COMBIEN": "Q4 · BY HOW MUCH",
        "Q5 · TES OUTILS": "Q5 · YOUR TOOLS",
        "Q6 · CE QUI TE FRUSTRE": "Q6 · WHAT FRUSTRATES YOU",
        "Quand tu es sur place": "When you're there",
        "Rajouter le retour": "Add the return",
        "Rappels avant tes vols": "Reminders before your flights",
        "Rechercher une devise…": "Search a currency…",
        "Rejoins mon voyage sur Tripnest.": "Join my trip on Tripnest.",
        "Restaurants, hôtels et lieux à visiter.": "Restaurants, hotels and places to visit.",
        "Retirer des coups de cœur": "Remove from favorites",
        "Retirer des sauvés": "Remove from saved",
        "Retirer des spots sauvés": "Remove from saved spots",
        "Retour aux voyages": "Back to trips",
        "Retour · date à définir": "Return · date to be set",
        "Rien de précis": "Nothing specific",
        "RÉSULTAT": "RESULT",
        "Réflexion": "Reflection",
        "Réservations, horaires, documents": "Bookings, schedules, documents",
        "SIÈGE": "SEAT",
        "SPOTS\nSAUVÉS": "SAVED\nSPOTS",
        "Saisir le billet": "Enter the ticket",
        "Sauvegarder mon plan →": "Save my plan →",
        "Selon tes dépenses": "Based on your spending",
        "Sera invité après l'enregistrement": "Will be invited after saving",
        "Siège": "Seat",
        "Siège / place": "Seat / spot",
        "Sois ambitieux·se. On va t'y aider.": "Be ambitious. We'll help you get there.",
        "Sois honnête — c'est ce qu'on va régler ensemble.": "Be honest — that's what we'll fix together.",
        "Sortir de ma zone": "Get out of my comfort zone",
        "Souvenirs, spots, budget et planning": "Memories, spots, budget and planning",
        "Spots sauvegardés": "Saved spots",
        "Spots sélectionnés": "Selected spots",
        "Stratégie d'économie": "Savings strategy",
        "Style de voyage défini": "Travel style defined",
        "Suggestion de spots à proximité": "Nearby spot suggestions",
        "Suivi budget": "Budget tracking",
        "Suivi des dépenses du voyage sélectionné : catégories, total dépensé et budget restant.": "Spending tracking for the selected trip: categories, total spent and remaining budget.",
        "Suivre dépenses": "Track expenses",
        "Sélection adaptée à ton style": "Selection tailored to your style",
        "TERMINÉ": "DONE",
        "TON BUDGET MOYEN": "YOUR AVERAGE BUDGET",
        "TON DÉFI": "YOUR CHALLENGE",
        "TON OBJECTIF D'ÉCONOMIE": "YOUR SAVINGS GOAL",
        "TON PROCHAIN VOYAGE": "YOUR NEXT TRIP",
        "Ta motivation": "Your motivation",
        "Tes clichés et souvenirs de ce voyage.": "Your snapshots and memories from this trip.",
        "Tes dépenses payées apparaîtront ici.": "Your paid expenses will appear here.",
        "Tes lieux favoris restent rattachés au bon voyage.": "Your favorite places stay linked to the right trip.",
        "Tes lieux importants : restaurants, hôtels, activités… reliés à un voyage.": "Your key places: restaurants, hotels, activities… linked to a trip.",
        "Tes lieux importants pour le voyage sélectionné : restaurants, hôtels, activités… Chaque spot est relié à un voyage.": "Your key places for the selected trip: restaurants, hotels, activities… Each spot is linked to a trip.",
        "Tes prochains voyages apparaissent dès que tu les crées.": "Your next trips appear as soon as you create them.",
        "Tes spots": "Your spots",
        "Tes voyages terminés": "Your completed trips",
        "Tes vrais lieux à retrouver": "Your real places to find again",
        "Titre du voyage": "Trip title",
        "Ton ami pourra ajouter ou changer le voyage.": "Your friend will be able to add or change the trip.",
        "Ton ami verra le voyage en direct sans modifier.": "Your friend will see the trip live without editing.",
        "Ton billet d'avion": "Your plane ticket",
        "Ton billet de ferry": "Your ferry ticket",
        "Ton billet de train": "Your train ticket",
        "Ton espace": "Your space",
        "Ton objectif": "Your goal",
        "Ton plan": "Your plan",
        "Ton profil": "Your profile",
        "Ton profil voyageur": "Your traveler profile",
        "Toujours obsolète, jamais à jour": "Always outdated, never up to date",
        "Tous": "All",
        "Tous tes voyages planifiés ou réalisés. Crée, modifie, archive et invite des amis pour qu’ils puissent voir et gérer le voyage avec toi.": "All your planned or completed trips. Create, edit, archive and invite friends so they can view and manage the trip with you.",
        "Tout ça à la fois": "All of it at once",
        "Trajet à définir": "Route to be set",
        "Trop de temps à saisir": "Takes too long to enter",
        "Tu as ce qu'il faut": "You've got what it takes",
        "Tu n'es pas seul·e": "You're not alone",
        "Tu pourras modifier le voyage avec moi.": "You'll be able to edit the trip with me.",
        "Tu pourras regarder le voyage en direct, sans le modifier.": "You'll be able to watch the trip live, without editing it.",
        "Un grand voyage par an": "One big trip a year",
        "Une autre app": "Another app",
        "Une feuille Excel / Google Sheets": "An Excel / Google Sheets file",
        "Une seule réponse — celle qui te ressemble le plus.": "One answer only — the one that fits you most.",
        "Une à deux fois par an": "Once or twice a year",
        "VOYAGE EN COURS": "ONGOING TRIP",
        "VOYAGE PLANIFIÉ": "PLANNED TRIP",
        "VOYAGE TERMINÉ": "COMPLETED TRIP",
        "Valider le billet": "Confirm the ticket",
        "Visiter 3 nouvelles destinations": "Visit 3 new destinations",
        "Voir l'onglet Voyages": "See the Trips tab",
        "Voir les photos": "See photos",
        "Voir les spots": "See spots",
        "Voir mon plan de voyage →": "See my travel plan →",
        "Voir mon plan personnalisé →": "See my personalized plan →",
        "Vol à suivre": "Flight to track",
        "Voyage": "Trip",
        "Voyage aller simple": "One-way trip",
        "Voyage en cours": "Ongoing trip",
        "Voyage fait": "Trip done",
        "Voyage introuvable": "Trip not found",
        "Voyage planifié": "Planned trip",
        "Voyage terminé": "Trip completed",
        "Voyage à deux": "Trip for two",
        "Voyages réels": "Real trips",
        "Vue d'ensemble de ton voyage en cours : statut, budget, spots, souvenirs et planning.": "Overview of your ongoing trip: status, budget, spots, memories and planning.",
        "Vue d’ensemble de ton voyage en cours : carte, résumé du trajet et accès rapide aux billets.": "Overview of your ongoing trip: map, route summary and quick access to tickets.",
        "Vérité": "Truth",
        "cliché": "snapshot",
        "clichés": "snapshots",
        "À activer": "To enable",
        "À compléter avec tes étapes": "To complete with your stages",
        "À construire": "To build",
        "À créer": "To create",
        "À définir": "To be set",
        "À refaire": "To do again",
        "ÉCONOMIE": "SAVINGS",
        "Économiser 500€+ sur mes voyages": "Save €500+ on my trips",
        "Économiser sur mes voyages": "Save on my trips",
        "Écrans principaux reliés": "Main screens connected",
        "État des lieux": "Current situation",
        "%d billet(s) · %@": "%d ticket(s) · %@",
        "→ Budget total : %@": "→ Total budget: %@",
        "%d fond(s) stocké(s) · %@": "%d fund(s) stored · %@",
        "≈ %@/jour": "≈ %@/day",
        "Modifier %@": "Edit %@",
        "« %@ » sera définitivement supprimé.": "“%@” will be permanently deleted.",
        "« %@ » sera déplacé dans Voyages passés.": "“%@” will be moved to Past trips.",
        "« %@ » sera enregistré dans Voyages passés.": "“%@” will be saved to Past trips.",
        "« %@ » et toutes ses dépenses, vols et spots seront effacés.": "“%@” and all its expenses, flights and spots will be erased.",
        "%d ami sur ce voyage": "%d friend on this trip",
        "Étape %d / %d": "Step %d / %d",
        "%d jour": "%d day",
        "%d jours": "%d days",
        "%d voyage terminé": "%d completed trip",
        "%d voyages terminés": "%d completed trips",
        "%d enregistré": "%d saved",
        "%d enregistrés": "%d saved",
        "%d enregistré à %@": "%d saved in %@",
        "%d enregistrés à %@": "%d saved in %@",
        "%d/%d lignes": "%d/%d lines",
        "DANS %d JOURS": "IN %d DAYS",
        "EN COURS · JOUR %d/%d": "ONGOING · DAY %d/%d",
        "En cours · Jour %d/%d": "Ongoing · Day %d/%d",
        "Départ le %@": "Departure on %@",
        "Je te partage mon voyage « %@ » sur Tripnest. %@": "I'm sharing my trip “%@” with you on Tripnest. %@",
        "Ton voyage vers %@ · %@": "Your trip to %@ · %@",
        "Dans 1 h : %@": "In 1 hr: %@",
        "%@ sera ajouté au voyage en mode %@.": "%@ will be added to the trip in %@ mode.",
        "%@ est déjà prêt à être invité.": "%@ is already ready to be invited.",
        "%@ recevra l'invitation après l'enregistrement en mode %@.": "%@ will receive the invitation after saving in %@ mode.",
        "Ajoute ton %@ pour retrouver horaires et détails ici.": "Add your %@ to find schedules and details here.",
        "Hors-ligne · %@": "Offline · %@",
        "Dans %d jours": "In %d days",
        "%d cliché": "%d snapshot",
        "%d clichés": "%d snapshots",
        "Aller-retour": "Round-trip",
        "Aller simple": "One-way",
        "Aller": "Outbound",
        "Retour vers": "Return to",
        "Départ · %@": "Departure · %@",
        "Retour · %@": "Return · %@",
        "%@ · Aller-retour": "%@ · Round-trip",
        "%@ · Aller simple": "%@ · One-way",
        "Retour %@": "Return %@",
        "%@, sélectionné": "%@, selected",
        "Aller sans retour": "One-way",
        "Regarder seulement": "View only",
        "Restaurants": "Restaurants",
        "modification": "editing",
        "lecture seule": "view only",
        "Repas": "Meals",
        "En cours": "Ongoing",
    ]
}
